name: DevCard

on:
  push:
    branches:
    - main

  workflow_dispatch:
  
  schedule:
  - cron: "0 0 * * *"

jobs:
  devcard:
    runs-on: ubuntu-latest
    steps:
      - name: devcard
        uses: dailydotdev/devcard@2.0.6
        with:
          devcard_id: ${{ secrets.DEVCARD_ID }}
